### ISSUE TITLE
Simple Sample Dataset of Vector Tiles

### ISSUE THREAD

**Issue by hallahan** [mapbox/vector-tile-spec#10]
Where can we find some good vector tiles to play with and decode? I'm talking about maybe a big zip full of tiles, not an obfuscated SQLite MBTiles container.

**Comment by pnorman** [comment]
I'll look at doing up some examples. They're useful to have, as when implementing a decoder (like the person above) you currently have to go to another repo.

**Comment by mapsam** [comment]
@hallahan and @pnorman - mighty late to the game here, but we have a number of valid and invalid examples over at https://github.com/mapbox/mvt-fixtures now. There aren't any that contain a ton of data, though. I'd be curious to hear if there are any you'd wish to see.

**Comment by hallahan** [comment]
Thanks @mapsam . Interesting throwback in time. Good to know!
