### ISSUE TITLE
Add Non-scalar properties to the version 3.0

### ISSUE THREAD

**Issue by ethervoid** [mapbox/vector-tile-spec#109]
As you can see in the Protocol buffers specification is possible to define non-scalar properties as you can see [here](https://developers.google.com/protocol-buffers/docs/proto3#json).

What if the MVT specification includes that kind of options in the [`Values` part](https://github.com/mapbox/vector-tile-spec/blob/master/2.1/vector_tile.proto#L17-L28) to be able to pass array-based or composite properties that could be used for different purposes like for example interactivity.

I assume that in the past this [was not added to the specification](https://www.mapbox.com/vector-tiles/specification/#how-to-encode-attributes-that-arent-strings-or-numbers) because the version 2 of the protocol buffers didn't support it, the version 3 was released the 26th of July, 2016 and the last change in the .proto file for MVT was the 5th June 2016 but now we are able to use if assuming the 3.0 proto version is going to use the proto3 Spec :)

**Comment by jfirebaugh** [comment]
Yes, we're probably going to do this for v3. See #75.

**Comment by ethervoid** [comment]
Cool! Thank you
