### ISSUE TITLE
Delta encoding between features

### ISSUE THREAD

**Issue by ericfischer** [mapbox/vector-tile-spec#122]
If we do change the format incompatibly to improve compression, it may also be worth encoding each feature's location as a delta from the previous one, instead of beginning every feature with a `moveto` from (0,0).

**Comment by joto** [comment]
This would make it basically impossible to only decode the geometry of some of the features for instance when filtering based on the properties.

**Comment by ericfischer** [comment]
Thanks. Not practical in spite of the improved performance.
