### ISSUE TITLE
Support for single level GeoJSON GeometryCollection?

### ISSUE THREAD

**Issue by chaeron** [mapbox/vector-tile-spec#138]
Not having support for GeometryCollection in MapBox has caused me some headaches.

It's a standard part of GeoJSON, and as such, should be supported.  Worth noting is that the GeoJSON standard does state that GeometryCollections should NOT be nested....so support of a single level of GeometryCollection should be a reasonable thing to implement.  See: https://tools.ietf.org/html/rfc7946#section-3.1.8

**Comment by joto** [comment]
Duplicate of #110 .
