### ISSUE TITLE
converting to/from other formats

### ISSUE THREAD

**Issue by summer4096** [mapbox/vector-tile-spec#21]
Hi, I've got a question and I hope this is an alright place to put it.

There are a number of vector tile sources out there that use geojson. Is it possible to convert the tiles defined in this repo into geojson, or vice versa? If so, are there any known implementations?

**Comment by mapsam** [comment]
@devTristan @wboykinm Much has happened since late 2014, but worth noting that `addGeoJSON` (and many others) are now included in Node Mapnik's documentation: http://mapnik.org/node-mapnik/documentation/3.5/#mapnik-vectortile/addgeojson
