### ISSUE TITLE
Compression

### ISSUE THREAD

**Issue by pnorman** [mapbox/vector-tile-spec#27]
Currently the specification does not allow compression, but some PBFs seen in the wild are compressed, and not at the transport layer (HTTP).

The specification should be explicit on if compression is allowed.

**Comment by pnorman** [comment]
> Currently we do not have any text in version 2.0 pull request about compression, but I feel we should likely add something at least describing it? I understand that it is often dealt with on a transport level by the browsers, but for server side processing in the wild there are a variety of compressed and uncompressed tiles. If anyone would like to create a pull request to the v2-development branch with these changes it would be GREATLY appreciated

I'm actually happy with how the spec is silent on compression.

A m-v-t file is not compressed. It is often useful to compress m-v-t when storing them, but then you have a compressed m-v-t file, not a m-v-t file. Analogously, planet-latest.osm.bz2 is bzipped XML, not just XML.

With transport-level compression and HTTP the content is uncompressed, and the gzip encoded content is compressed.

Specifications for storage (e.g. mbtiles, disk layouts, etc) should address if the tiles have compression applied to them.

-----

> It matters when you are making mbtiles too, because if you don't compress (or if you use zlib instead of gzip) you can't upload it

The m-v-t spec doesn't address uploading, just the format of a single vector tile. As it stands, mbtiles cannot store vector tiles, only [png or jpg](https://github.com/mapbox/mbtiles-spec/blob/master/1.2/spec.md#content-1)

#39 proposes language which is clearer on the vector tile being different than the system that encodes its bounds and projection (TMS numbering, google maps tile numbers, etc)

**Comment by kkaefer** [comment]
@ericfischer, I agree with @pnorman in that the respective storage formats/APIs should handle compression, not the vector tile spec.

**Comment by ericfischer** [comment]
Sounds good to me to address this in the mbtiles spec instead.

**Comment by flippmoke** [comment]
All of this sounds great to me! We probably should encourage the use of `.mvt.gz` ?

**Comment by pnorman** [comment]
yes, if storing gzipped mvts, .mvt.gz makes sense for a filename.

**Comment by flippmoke** [comment]
Have we reached a general agreement around this, if so I am going to close the ticket to mark this task as closed.

**Comment by kkaefer** [comment]
Yes.
