### ISSUE TITLE
Split implementations into producers and consumers

### ISSUE THREAD

**Issue by pnorman** [mapbox/vector-tile-spec#34]
https://github.com/mapbox/vector-tile-spec/wiki/Implementations could be clearer if it split apart into producers and consumers of vector tiles. Some do both, but many are just one side.

There may also be some duplication - I see more than one link which is Mapnik under the hood. Is it useful to list all libraries and applications which use mapnik-vector-tile?

**Comment by tmcw** [comment]
@pnorman the wiki is editable by anyone, right?

**Comment by pnorman** [comment]
> @pnorman the wiki is editable by anyone, right?

Yes.

**Comment by tmcw** [comment]
Feel free to submit a PR to https://github.com/mapbox/awesome-vector-tiles with this change.
