### ISSUE TITLE
Update Comments in Proto File

### ISSUE THREAD

**Issue by flippmoke** [mapbox/vector-tile-spec#41]
While a great amount of text has changed in the version 2 text specification README, the protob file has not been heavily changed. https://github.com/mapbox/vector-tile-spec/pull/39

The comments in the file should be updated to match the wording of the specification and more comments could be added to perhaps better explain some fields (or link to their requirements in the the README?)

**Comment by pnorman** [comment]
> link to their requirements in the the README

I recommend this
