### ISSUE TITLE
Register MIME type

### ISSUE THREAD

**Issue by flippmoke** [mapbox/vector-tile-spec#48]
Assuming specified mime type for version 2.0 is accepted, we should register the MIME type to make it official. 

/cc @sgillies @pnorman

**Comment by pnorman** [comment]
Is the process publish a spec using a registration required mime type then register with IANA or to publish a spec then register against the spec?

Or, because it's a vnd tree name, can we point at the existing spec for a registration? I *think* this is possible.

**Comment by sgillies** [comment]
@flippmoke there's a submission form linked from http://www.iana.org/assignments/media-types/media-types.xhtml and directions in http://tools.ietf.org/html/rfc6838. IIRC, my `application/vnd.geo+json` submission was approved in ~1.5 weeks.

Vector tiles do not qualify for the standards tree (http://tools.ietf.org/html/rfc6838#section-3.1) but do qualify for the vendor (vnd) tree. I suggest `application/vnd.mvt`.

GeoJSON's info (http://www.iana.org/assignments/media-types/application/vnd.geo+json) is as good a template as any. You'll definitely want to make sure there's a canonical URL for the `.proto` file in the MVT info since interop hinges on that.

**Comment by jfirebaugh** [comment]
Is there a reason to use a (IMO cryptic) abbreviation in the MIME type, or could we switch to one of the following:

* `application/vnd.mapbox-vector-tile
* `application/vnd.vector-tile`

Should the MIME type encode the carrying format (protobuf), similar to the way that `application/vnd.geo+json` encodes JSON?

**Comment by sgillies** [comment]
@jfirebaugh `+protobuf` doesn't meet the guidelines (in http://tools.ietf.org/html/rfc6838#section-4.2.8) for a media type suffix. There was a protocol buffers draft a few years ago, https://tools.ietf.org/html/draft-rfernando-protocol-buffers-00, but it expired and was never published.

**Comment by flippmoke** [comment]
>Is there a reason to use a (IMO cryptic) abbreviation in the MIME type, or could we switch to one of the following:
>
> * application/vnd.mapbox-vector-tile
> * application/vnd.vector-tile

I have no objection to either of the suggestions, I honestly just used an abbreviation because thats how many are out in the wild.

**Comment by flippmoke** [comment]
Following up on what we have talked about regarding the name, I see nothing about the style of the name required in https://tools.ietf.org/html/rfc2048#section-2.2.2, so I think @jfirebaugh's suggestions will work fine. I will change the document to one of these.

**Comment by pnorman** [comment]
@flippmoke Will you pursue the IANA registration, or should I do a registration on behalf of a third party?

**Comment by flippmoke** [comment]
@pnorman I will pursue one and coordinate with @sgillies

**Comment by flippmoke** [comment]
I will post this here as a general question:

Do optional parameters make sense for us to register with the MIME type. Due to the fact that vector tiles do not alone contain all the information necessary to process them, does it make sense to have optional header parameters that provide information such as:

- Projection
- Tile X, Y, Z
- Tile Bounds

**Comment by tmcw** [comment]
I don't think that we should implement optional header parameters yet: everything but x/y/z is a can of worms and x/y/z is already in the URL. MIME is a good first step and we can tackle header parameters once we have better answers around projections and a concrete usecase.

**Comment by flippmoke** [comment]
I have submitted the registration, now waiting on their approval or comments

**Comment by flippmoke** [comment]
Removed this from the v2.0 milestone, but will update as more information becomes available.

**Comment by flippmoke** [comment]
http://www.iana.org/assignments/media-types

We are now an official mime type.

**Comment by stevage** [comment]
For anyone else stumbling across this, the registered type is `vnd.mapbox-vector-tile`
