### ISSUE TITLE
Incorrect Description of Extent

### ISSUE THREAD

**Issue by flippmoke** [mapbox/vector-tile-spec#54]
Currently the spec states:

> For example, if a tile has an extent of 4096, values between 0 and 4095 are considered within the tile's extent. A point at (0,10) or (4095,10) is within the extent of the tile. A point at (-1,10) or (4096,10) is outside the extent of the tile.

This is incorrect because the edges of the tile should be 0 and 4096, therefore, values between 0 and 4096 are considered within the tile's extent!

This was a failure of my part during writing this section and does not reflect how "v1 tiles were being created".  I think it is important to change the wording of this section to properly reflect that the edges of the tile are 0 and 4096 for an extent of 4096.

**Comment by flippmoke** [comment]
I feel I need to check a variety of implementations on this because the original `proto` file states:

> The bounding box in this tile spans from 0..4095 units

if others are actually using 0 to 4095, I should leave it as it is...

**Comment by flippmoke** [comment]
Mapnik-Vector-Tile operates on the assumption of 0 to 4096
Vector-Tile-JS operates on the assumption of 0 to 4096 - https://github.com/mapbox/vector-tile-js/blob/master/lib/vectortilefeature.js#L130-L132

**Comment by flippmoke** [comment]
Vector-Tile-Py operates on 0-4096 - https://github.com/mapbox/vector-tile-py/blob/master/vector_tile/renderer.py

**Comment by flippmoke** [comment]
The C# implmentation seems to do 0-4096 as well https://github.com/bertt/mapbox-vector-tile-cs/blob/master/src/Coordinate.cs#L13-L15

**Comment by flippmoke** [comment]
The Java implementation seems to be 0-4096 as well: https://github.com/ElectronicChartCentre/java-vector-tile/blob/master/src/main/java/no/ecc/vectortile/VectorTileEncoder.java#L102-L110

**Comment by jfirebaugh** [comment]
How about saying something like "0 indicates a position precisely on the top or left edge of the tile, and 4096 a position precisely on the bottom or right edge"?

**Comment by kkaefer** [comment]
I'm :-1: on 4096 because it would mean that a tile is 4097 units wide.

**Comment by ericfischer** [comment]
The thing that isn't clearly specified is that the coordinates refer to the top left corner of each pixel, not to the middle of the pixel, so the 4096th unit is the bottom-right edge of the tile, the top-left edge of the adjacent tile.

**Comment by flippmoke** [comment]
@kkaefer it is `4096` units wide, just the last unit is included as well and @ericfischer is right we should likely clarify the "placement of the pixel"

**Comment by jfirebaugh** [comment]
Yes, what @ericfischer said.

@flippmoke The portion of the spec that you quoted is correct as written.

> For example, if a tile has an extent of 4096, values between 0 and 4095 are considered within the tile's extent. A point at (0,10) or (4095,10) is within the extent of the tile. A point at (-1,10) or (4096,10) is outside the extent of the tile.

(4096, y) _is_ outside the extent of a 4096-extent tile, for any value of y.

I'm not sure the code examples you linked are actually inconsistent with this definition.

**Comment by jfirebaugh** [comment]
It may be that "outside the extent" is not a useful concept in practical terms. Is it included to clarify the clipping behavior in cases where there's zero buffering, or what?

**Comment by flippmoke** [comment]
@jfirebaugh the code currently in all the libraries makes it such that if the `extent` is `4096` the valid range of values is `[0,4096]`. The wording of 2.0 makes it `[0,4096)` in my opinion.

**Comment by jfirebaugh** [comment]
@flippmoke "valid" in what sense? In practice, (4097, 4097) is a perfectly valid coordinate due to buffering.

**Comment by flippmoke** [comment]
@jfirebaugh sorry valid is not what I really meant, I should say "within" if there is no buffering it should be expected that all values would be [0,4096] range?

**Comment by kkaefer** [comment]
Well, 4096 is *just* on the edge, like 0 is *just* on the other edge. I guess it's a philosophical and/or mathematical discussion of whether that's "within" or not.

**Comment by jfirebaugh** [comment]
Assuming tiles with no buffering, what subset of the four z1 tiles should contain the point feature representing null island?

**Comment by flippmoke** [comment]
@jfirebaugh I believe all current implementations would have the point feature.

**Comment by jfirebaugh** [comment]
@flippmoke I'm not asking for what behavior existing implementations happen to have, I'm asking what behavior we want the specification to require. The answer could be one of the following:

* "All four z1 tiles should contain the point feature representing null island."
* "Only the bottom right z1 tile should contain the point feature representing null island."
* Some other subset of z1 tiles (but if you give this answer I'm going to be very surprised).

I know which answer I believe is correct, but I'm interested to hear what others think.

**Comment by ericfischer** [comment]
I'm still really torn about this. On the one hand, asking for no buffer is clearly asking for exactly one copy of each feature. On the other hand, with line and polygon features, you really do need to go to 4096 instead of 4095 if you don't want blatant discontinuity, and it seems weird to treat points differently.

**Comment by flippmoke** [comment]
The wording for this was updated in https://github.com/mapbox/vector-tile-spec/pull/56 by @ericfischer I think this is a reasonable wording currently. I think non-repeating features and a change in the range of the extent is something we would have to consider in a major version bump.

**Comment by jfirebaugh** [comment]
I'm fine with releasing with the wording change in 2.1, but I don't think it really resolves the fundamental issue here, which is more a question about the requirements on encoders for left/bottom-edge clipping.

**Comment by ericfischer** [comment]
@jfirebaugh I've changed Tippecanoe to follow Mapnik's behavior, which is to put the null island point in all four tiles. I think either 1-tile or 4-tile is defensible but that 4-tile is the most useful for renderers and the most consistent with line and polygon requirements.

**Comment by flippmoke** [comment]
@jfirebaugh @ericfischer I am going to close this ticket and use the current wording, but I feel that we should definitely revisit this conversation when we update the spec in a future version.
