### ISSUE TITLE
Clarify .mvt as Mapbox Vector Tile

### ISSUE THREAD

**Issue by mapsam** [mapbox/vector-tile-spec#57]
Per discussion with @springmeyer, it seems important to be explicit about what `.mvt` stands for or, rather, what we'd like it to stand for from now on. There has been some confusion in regards to the [recent blog post](http://gisuser.com/2016/01/boundless-announces-mapbox-vector-tile-support-in-opengeo-suite/) calling them *Mapbox Vector Tiles*. Since `.mvt` is not a new concept, it can be conflated with *Mapnik Vector Tiles*.

**Proposal: officially call these *Mapbox Vector Tiles*.** by adding to [2.1 file extension](https://github.com/mapbox/vector-tile-spec/blob/master/2.0/README.md#21-file-extension) ... something like " ... `.mvt` (Mapbox Vector Tile) ... "

Would love some guidance on PR workflow @flippmoke!

**Comment by flippmoke** [comment]
@mapsam I am not sure we need to update the specification as it is the name of the specification? https://github.com/mapbox/vector-tile-spec#mapbox-vector-tile-specification
