### ISSUE TITLE
specify maximum extent

### ISSUE THREAD

**Issue by jfirebaugh** [mapbox/vector-tile-spec#59]
The specification should set an upper bound of **16,384** for the extent of a tile, so that decoders can safely use signed 16 bit integers to represent (potentially buffered) tile coordinates (as certain widely used decoders already do).

It should probably also specify that tile extents must be a power of 2.

cc @ansis

**Comment by ericfischer** [comment]
It would be nice to have this as a SHOULD for tile encoders instead of a MUST to leave open the possibility of someday again being able to encode sparse but high resolution data in low-zoom tiles.

**Comment by flippmoke** [comment]
Why must a tile extent be a power of 2? Additionally with the possibility of buffers, what is to guarantee that a signed 16 bit int would suffice. I am not sure that we should specify that at such a low value either.

**Comment by jfirebaugh** [comment]
You're right, it doesn't have to be a power of two, and consumers can always normalize to a lower precision during parsing (as Mapbox GL does as of https://github.com/mapbox/mapbox-gl-native/commit/4e0d1070f623811513e6800e4ac906d69958d66a). This is a non-issue.
