### ISSUE TITLE
Spec 2.1 Feature IDs in Example

### ISSUE THREAD

**Issue by ShibaBandit** [mapbox/vector-tile-spec#60]
> A feature MAY contain an id field. If a feature has an id field, the value of the id SHOULD be unique among the features of the parent layer.

Had a question on the example at the bottom of the 2.1 spec. It involves the conversion of some GeoJSON points into a vector tile. I noticed that the 'ID' field is the same for both point features in the vector tile. Is this valid?

Example in question:

> layers {
  version: 2
  name: "points"
  features: {
    id: 1
    tags: 0
    tags: 0
    tags: 1
    tags: 0
    tags: 2
    tags: 1
    type: Point
    geometry: 9
    geometry: 2410
    geometry: 3080
  }
  features {
    id: 1
    tags: 0
    tags: 2
    tags: 2
    tags: 3
    type: Point
    geometry: 9
    geometry: 2410
    geometry: 3080
  }
  keys: "hello"
  keys: "h"
  keys: "count"
  values: {
    string_value: "world"
  }
  values: {
    double_value: 1.23
  }
  values: {
    string_value: "again"
  }
  values: {
    int_value: 2
  }
  extent: 4096
}

**Comment by flippmoke** [comment]
`SHOULD` according to rfc 2119 which is listed at the top of the specification:
```
3. SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.
```
Therefore, it is actually valid. However, this was not intended to be this way in the example.

**Comment by ShibaBandit** [comment]
So SHOULD it be two different IDs in this case?

**Comment by flippmoke** [comment]
@ShibaBandit yep

**Comment by ShibaBandit** [comment]
@flippmoke Cool. Thank you sir.
