### ISSUE TITLE
Winding order in Mapbox tiles

### ISSUE THREAD

**Issue by bcamper** [mapbox/vector-tile-spec#61]
I was looking at Mapbox's Streets tiles to verify my understanding of the [winding orders](https://github.com/mapbox/vector-tile-spec/tree/master/2.1#4344-polygon-geometry-type) in spec v2.1:

> In the tile coordinate system (with the Y axis positive down and X axis positive to the right) this makes the exterior ring's winding order appear clockwise.

But the polygons I'm seeing in Streets v6 tiles don't match my expectation. For example, in tile `4826/6161/14` (loaded from https://b.tiles.mapbox.com/v4/mapbox.mapbox-streets-v6/14/4826/6161.vector.pbf), I checked a landuse poly with Mapbox's Vector Tile JS lib:

`JSON.stringify(tile.layers.landuse.feature(0).loadGeometry())`
`> "[[{"x":2195,"y":1735},{"x":2250,"y":2096},{"x":2778,"y":2015},{"x":2724,"y":1655},{"x":2195,"y":1735}]]"`

When these points are plotted with a Y-positive-down axis, the ring order appears counter-clockwise:

![screen shot 2016-02-18 at 6 08 22 pm](https://cloud.githubusercontent.com/assets/16733/13161258/a0814e26-d66a-11e5-83b0-c331ed77335e.png)

Maybe this is a known issue, or maybe am I confused? :) (I realized this isn't a spec issue per se but seemed relevant.) Thank you!

**Comment by springmeyer** [comment]
@bcamper We are still working on upgrading our tilesets to adhere to the v2 spec. This is a work in progress and currently waiting on https://github.com/mapnik/node-mapnik/pull/579 to be merged, pushed into a tagged release, and then used to regenerate `mapbox-streets`.

**Comment by bcamper** [comment]
Thanks! Just wanted to make sure I wasn't crazy.
