### ISSUE TITLE
Spec extension for (optional) inclusion of pre-computed labels / manually placed annotation?

### ISSUE THREAD

**Issue by mboeringa** [mapbox/vector-tile-spec#84]
This is something I have been wondering ever since I first read about Vector Tiles. Are there any plans for an (optional) extension of the spec to allow pre-computerd (placed) labels to be included in vector tiles?

The reason I am asking this is that, as far as I understand the whole vector tile thing up to now from the limited reading I did, labelling is currently fully dynamic and depends heavily on the devices hardware and browser to do the potentially hefty job of placing and showing labels, including collision detection etc.

While this may work for "simple" labelling rules, some GIS's like ArcGIS have pretty advanced labelling engines, who's results are likely very difficult or practically infeasible to replicate in style sheets and dynamic labelling in the browser using something like Mapbox GL-JS. There may even be a significant body of carefully manually placed annotations in GIS or CAD system datasets, like you see in large scale CAD files or topographic maps.

What I am essentially thinking of is the option to be able to grab a GIS or CAD "map", and output it to a specific zoom level in a tile with its full pre-computed labelling or annotation being stored 1:1 in vector tiles as a kind of "vector text overlay", so without any loss of styling and each glyph at its correct position, rotation, size and color as it was in the original GIS or CAD map (which would need to include stuff like text halos as well). Of course, labelling must be stored for specific zoom ranges, so multiple label sets would need to be included in the vector tile set. Fonts would probably need to be (optionally) included as well.

All of this would be a kind of multi-scale seamless vector tile equivalent of a "GeoPDF"

Of course, some fancy things that fully dynamic labels now offer, wouldn't be available for these pre-computed and placed labels. But that is not the point, these labels should be fixed, as having been placed with great care and deliberate.

Additionally, the ability of outputting these labels to a vector tile is of course not the responsibility of this VT specification, but must be implemented in a GIS or CAD, but with no option to do so in the VT standard, nothing will ever be possible in that direction...

Note that I have no real experience with Mapbox vector tiles from the developers perspective, this is just a user question, so bear with me if I mis-understood some of the rendering and styling workflow and technical challenges or details.

**Comment by jingsam** [comment]
You can just output your labeling layers from ArcGIS or CAD to symbol layers in vector tiles. Then you can style them as you wish.

**Comment by lucaswoj** [comment]
Hi @mboeringa! 

The vector tile spec as written accomodates this use case. You can add labels to vector tiles as point features. 

We make extensive use of this technique in Mapbox streets. For example the [`#road`](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#road) layer contains road line features and [`#road_label`](https://www.mapbox.com/vector-tiles/mapbox-streets-v7/#road_label) contains road label point features.

Good luck!
