### ISSUE TITLE
Partial decode of protobuf

### ISSUE THREAD

**Issue by TimSC** [mapbox/vector-tile-spec#86]
The version 2 spec says "Decoders SHOULD parse the version first to ensure that they are capable of decoding each layer." Is that achievable using the standard protobuf compiler generated code? Is a separate/custom protobuf parser needed to check this before reading the layer fully?

**Comment by jfirebaugh** [comment]
Yes, it's SHOULD rather than MUST due to the concern that some protobuf implementations may not allow control over order. See discussion in #64.
