### ISSUE TITLE
Override style when using ref

### ISSUE THREAD

**Issue by exotfboy** [mapbox/vector-tile-spec#99]
There is a `ref` property for layer configuration, as said in the document:

> References another layer to copy type, source, source-layer, minzoom, maxzoom, filter, and layout properties from. This allows the layers to share processing and be more efficient.

However sometimes we need to overwrite some properties after `ref` to a certain layer, for example, when we render a road, we should render that with a fill color and an outline color, and they share the common style expect for the `width` and `line-cap`, while the `width` is set in the `paint` , and the `line-cap` is set in the `layout`, so when I tried to override the `layout` properties, I got error `layout is forbidden in a ref layer`.

Is this intended?

**Comment by jfirebaugh** [comment]
Existing styles that use `ref` are still supported, but the `ref` property is no longer necessary -- Mapbox GL can now form refs automatically internally. So to avoid this error, you can just write your layers independently, each with the desired paint and layout properties, and not worry about using `ref`. (I've opened a PR updating the docs in #5329.)

**Comment by exotfboy** [comment]
Why I use `ref` is to avoid the duplicate style configuration for similar layers, for example they may share the same filter with a lot of stops, once we need to change a certain value, we should change all of them if we write the styles independently. 

Now the `ref` will be removed?
